name: Reset News Sitemap

# Run every 2 days at midnight
on:
  schedule:
    - cron: "0 0 */2 * *"  # Adjust as needed (runs every 2 days at midnight UTC)

jobs:
  reset_sitemap:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Create or overwrite news_sitemap.xml with initial content
    - name: Initialize news_sitemap.xml
      run: |
        echo '<?xml version="1.0" encoding="UTF-8"?>' > news_sitemap.xml
        echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"' >> news_sitemap.xml
        echo '        xmlns:news="http://www.google.com/schemas/sitemap-news/0.9">' >> news_sitemap.xml
        echo '' >> news_sitemap.xml
        echo '</urlset>' >> news_sitemap.xml

    # Commit and push changes if there are modifications
    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add news_sitemap.xml
        git commit -m "Initialize news_sitemap.xml"
        git push
      env:
        # Ensures GitHub token is used for pushing changes
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
